// Portfolio data — projects, profile, contact
window.PROFILE = {
  name: "Sorawit Sukudom",
  nickname: "Tai",
  role: "Designer & Visual Storyteller",
  location: "Dieburg, Germany",
  email: "sorawit.sukudom@gmail.com",
  phone: "+49 1551 0965507",
  linkedin: "linkedin.com/in/sorawit-sukudom",
  linkedinUrl: "https://www.linkedin.com/in/sorawit-sukudom/",
  tiktok: "@astroscopeth",
  website: "url-shortener.me/E5MP",
  websiteUrl: "https://url-shortener.me/E5MP",
  manifesto: "This portfolio was written by a human. I believe that while AI helps us work faster, only humans can create stories that truly connect with people.",
  intro: "Master's student in Expanded Media at Hochschule Darmstadt. Six years of UX/UI, brand and motion design across global names — McDonald's, GMM Grammy, Grab, SCB. I move between research-driven product work and storytelling that has to land in seconds.",
  forRole: {
    company: "h_da · Informatik · SecureBot",
    role: "HiWi (m/w/d) — Frontend Design",
    note: "An interdisciplinary research project on AI-supported cybersecurity learning. This portfolio is a focused selection for that application.",
  },
};

window.PROJECTS = [
  {
    id: "tropfin",
    no: "01",
    year: "2022 — 2025",
    title: "TROPFIN",
    kicker: "B2B Platform",
    role: "UI Designer · Team of 4",
    type: "Product",
    image: "assets/proj-05.png",
    summary: "A B2B trading platform connecting tropical-fruit factories and buyers across Europe and Asia. Owned the design system, marketing site and platform UI end-to-end across three years.",
    problem: "The legacy enquiry workflow lived in spreadsheets and email threads. Buyers couldn't see which factories matched their specs without phoning the team.",
    approach: "Built a modular design system in Figma — typography, components, illustration kit. Mapped the enquiry → match → offer flow into a structured UI with status colours, inline filters and saved markups.",
    outcome: "50% improvement in content-flow performance and user conversion. Visual system used across web, app, sales decks and trade-show booths.",
    tags: ["Figma", "Illustrator", "Design System", "B2B"],
    awards: null,
  },
  {
    id: "carbon-wallet",
    no: "02",
    year: "2021",
    title: "Carbon Wallet",
    kicker: "Mobile Application",
    role: "UX/UI Designer · Team of 3",
    type: "Product",
    image: "assets/proj-07.png",
    summary: "A behavioural app that turns everyday low-carbon choices — recycling, transit, energy use — into a savings wallet you can actually watch grow.",
    problem: "Sustainability apps tend to lecture. We needed people to want to come back daily, the way they open a banking app.",
    approach: "Designed a dashboard around a single growing tree metaphor; layered in waste-separation logging, location-aware tips and a daily-login economy. Worked closely with the energy-data team at Vekin Thailand.",
    outcome: "Winner of the ASEAN Energy Awards 2021 (Cutting-Edge Technology) and selected for the depa Smart City Accelerator Program 2021.",
    tags: ["Figma", "After Effects", "Sustainability", "Mobile"],
    awards: ["ASEAN Energy Awards 2021 — Winner", "depa Smart City Accelerator 2021"],
  },
  {
    id: "wavering",
    no: "03",
    year: "2020",
    title: "Wavering",
    kicker: "Interactive Game · Senior Project",
    role: "Product Owner, Designer, Developer",
    type: "Self-initiated",
    image: "assets/proj-10.png",
    summary: "An interactive mobile game about bipolar disorder. You play a small ship across moods — happiness, sadness, mania, depression — each one rewriting the physics of the sea.",
    problem: "Most mental-health content is read, not felt. I wanted to communicate what destabilised emotion feels like to someone who has never lived it.",
    approach: "Ten prototype iterations. Primary colours mark extreme emotion; black-and-white tones mark depression. Each version tested wave physics, tilt, blood/health systems and pacing — V1's physics broke on phones, V8 added a health system that slowed the ship, V10 added cutscenes and chapter transitions.",
    outcome: "A working prototype, a research-backed visual language for emotion, and a playable framing of an invisible illness.",
    tags: ["Game Design", "Unity", "Storytelling", "Research"],
    awards: null,
  },
  {
    id: "little-bobby",
    no: "04",
    year: "2020",
    title: "Little Bobby",
    kicker: "Pre-school Animation",
    role: "Team Lead · Animator · Team of 4",
    type: "Animation",
    image: "assets/proj-08.png",
    summary: "A short animated series about Bobby, a small star preparing for an adventure to the Candy Galaxy. Designed to teach pre-schoolers everyday self-care.",
    problem: "Children learn through repetition with characters they trust. We needed protagonists with strong personalities that read in a single silhouette.",
    approach: "Led a team of four. Built character bibles for Bobby, Luke, Bell and the mother Beauty. Wrote two episodes; directed key visuals; animated the adventure sequences.",
    outcome: "1st runner-up — National Pre-school Animation Award.",
    tags: ["Animation", "Storyboarding", "Character Design", "Team Lead"],
    awards: ["1st Runner-up — Pre-school Animation"],
  },
  {
    id: "gistda",
    no: "05",
    year: "2024",
    title: "Gistda Suvarnabhumi",
    kicker: "Cultural Heritage Platform",
    role: "UI Designer · Team of 3",
    type: "Product",
    image: "assets/proj-06.png",
    summary: "Web platform for Thailand's Geo-Informatics agency mapping the ASEAN co-cultural heritage of the Suvarnabhumi region — historical sites, civilisations, ancient trade routes.",
    problem: "Geospatial-archive tools usually look like government databases. The content deserved a cinematic, almost editorial feel that still held a researcher's depth.",
    approach: "Designed the homepage, civilisation-map view, location detail and timeline. Treated the map as the hero; pulled colour from satellite imagery and ancient-Thai manuscripts.",
    outcome: "A platform researchers and the public can both use — surfaced city periods, cultural evidence types, and the Belt-and-Road / India-Pacific strategic layers in one map.",
    tags: ["Photoshop", "Illustrator", "Cultural Heritage", "Web"],
    awards: null,
  },
  {
    id: "my-seoul",
    no: "06",
    year: "2019",
    title: "My Seoul",
    kicker: "SDG-aligned App Feature",
    role: "UI Designer · Intl. Team of 4",
    type: "Product",
    image: "assets/proj-09.png",
    summary: "A social-development module for an existing Seoul city app, designed during a UN-supported youth program at Hanyang University.",
    problem: "How do you bring SDG-aligned community action into an everyday city app without making it feel like homework?",
    approach: "Worked with researchers from four countries. Mapped user journeys against UN SDGs; designed onboarding, contribution loops and progress feedback.",
    outcome: "Research deck and clickable prototype delivered to Hanyang. Certificate in Social Development.",
    tags: ["Figma", "Research", "SDGs", "Cross-cultural"],
    awards: ["UN Youth Program · UNDP Asia-Pacific"],
  },
  {
    id: "mcdonalds",
    no: "07",
    year: "2021",
    title: "McDonald's Uniform System",
    kicker: "Product Design",
    role: "Product Designer",
    type: "Brand",
    image: "assets/proj-11.png",
    summary: "Uniform design collection for McDonald's HQ Thailand — polo shirts, caps, aprons, jackets, shirts — plus sister projects for Delta and Kobelco.",
    problem: "Corporate uniforms have to survive a kitchen, a logo system and a brand audit at the same time.",
    approach: "Worked with HR and brand teams on fit, fabric, reflective elements and velcro placement. Documented every garment from front, back and detail views.",
    outcome: "A full uniform collection rolled out across Thailand stores. Carried the same product-design discipline into the Delta jacket and Kobelco shirt.",
    tags: ["Product Design", "Brand", "Apparel"],
    awards: null,
  },
  {
    id: "scb",
    no: "08",
    year: "2021",
    title: "SCB E-Learning",
    kicker: "Internal Learning Platform",
    role: "UI Compositor",
    type: "Education",
    image: "assets/proj-09.png",
    summary: "An interactive e-learning module for Siam Commercial Bank covering credit policy and process — built to be navigated with a single mouse drag.",
    problem: "Compliance e-learning is famously skippable. The content team wanted something employees would actually finish.",
    approach: "Composited an interactive layout where the user drags across topic circles to reveal related content on the right. Built download flows for reference docs, and a guided 'next' progression for critical messages. Directly relevant to learning-platform UX work.",
    outcome: "A module the bank deployed internally, with measurably higher completion rates than the previous static slides.",
    tags: ["E-learning", "Interactive", "Banking", "Accessibility"],
    awards: null,
  },
  {
    id: "grab",
    no: "09",
    year: "2022",
    title: "GrabFood — M-size Campaign",
    kicker: "Motion · In-app Advertising",
    role: "Lead Motion Designer",
    type: "Motion",
    image: "assets/proj-16.png",
    summary: "A two-week in-app campaign for GrabFood Thailand. Lead motion designer on the M-size project at Rocketeer.",
    problem: "Two weeks, one campaign brief, multiple in-app ad sizes — and the metric is CTR, measured daily.",
    approach: "Worked with copy + art direction to land a single visual hook that survived being cropped to four formats. Iterated with performance data: kept what converted, cut what didn't.",
    outcome: "Significant CTR lift; campaign rolled into a follow-up sprint. Same formula reused for AIA and Bangkok Bank.",
    tags: ["After Effects", "Motion", "Campaign", "A/B Testing"],
    awards: null,
  },
  {
    id: "gmm",
    no: "10",
    year: "2019",
    title: "GMM Grammy — Music Campaigns",
    kicker: "Creative Design · Content Promote",
    role: "Creative Designer",
    type: "Motion",
    image: "assets/proj-15.png",
    summary: "Concert posters, single launches and social campaigns for GMM Grammy — Thailand's largest music label.",
    problem: "Music marketing is a fight for attention against an infinite scroll. Every post has roughly two seconds.",
    approach: "Editor on the Potato Magic Hours concert preview; co-creator on Pang Nakharin's 'KARMA' single launch (now 1M+ views); art direction on tour key visuals; live-stream director for Fool Step Band.",
    outcome: "One project crossed 260M views across Facebook, TikTok and YouTube. Built a sense of pace and copy I still use everywhere else.",
    tags: ["After Effects", "Premiere", "Editorial", "Live"],
    awards: null,
  },
  {
    id: "tiktok",
    no: "11",
    year: "2025 — present",
    title: "@astroscopeth",
    kicker: "TikTok · Self-initiated",
    role: "Creator · Editor · Researcher",
    type: "Motion",
    image: null,
    summary: "A personal experiment in short-form storytelling on TikTok. Three months in, three numbers I keep watching.",
    problem: "Could the storytelling instincts from concert promo work in a 15-second vertical format, in a market I'd just moved to?",
    approach: "Daily iteration loop: study what audiences in the German-speaking market respond to, hypothesise, post, read the analytics, adjust. Treat the algorithm like a research participant.",
    outcome: "320,000+ views and 195,000+ likes in three months. A live A/B-testing surface I plug back into client work.",
    tags: ["Short-form", "Editing", "Audience Research", "Analytics"],
    stats: [
      { value: "320K+", label: "views" },
      { value: "195K+", label: "likes" },
      { value: "3 mo.", label: "from zero" },
    ],
    awards: null,
  },
];

window.SKILLS = {
  "Design": ["Figma", "Component libraries", "Design systems", "Prototyping", "Wireframing"],
  "Visual": ["Brand identity", "Editorial layout", "Photoshop", "Illustrator", "Typography"],
  "Motion & Story": ["After Effects", "Premiere", "Storytelling", "Storyboarding", "Copywriting"],
  "Research": ["Audience research", "A/B testing", "KPI monitoring", "Analytics", "Cross-cultural"],
  "Frontend & Tech": ["HTML/CSS basics", "BITV 2.0 awareness", "Accessibility (WCAG)", "CMS", "Generative AI workflow"],
};

window.JOURNEY = [
  { y: "2025—", label: "M.A. Expanded Media", place: "h_da Darmstadt" },
  { y: "2022–25", label: "UX/UI Designer", place: "Tropfin · Bangkok" },
  { y: "2022–23", label: "Graphic Designer", place: "Rocketeer · Bangkok" },
  { y: "2021", label: "Graphic Design Coordinator", place: "McDonald's HQ Thailand" },
  { y: "2019", label: "Creative Designer", place: "GMM Grammy" },
  { y: "2019", label: "Cert. Social Development", place: "Hanyang University · Seoul" },
  { y: "2016–20", label: "B.A. Interactive & Multimedia Design", place: "Srinakharinwirot University" },
];
